### ISSUE TITLE
Performance to slow

### ISSUE THREAD

**Issue by ghost** [Alexander-0x80/Beauty-of-roots#1]
Hi Alexander: thanks for your code.

I run roots.py on my computer and when the degree is larger than 20 it  got very slow. for degree >= 22 it's expected to run a ｗhole day.

I saw you used a list and append the roots to it, and  list will get reallocated many times, I think this is the bottleneck in the performance.

May be you should declare a numpy array of size degree \* 2**degree, and assign roots to this array. It runs much faster on my computer (45mins for d=22)

Another tip: when assigning HSV colors to the img, you used two for loops and this can be simplified further. np.where( Z > 0) would find the elements in Z that are >0, and then one can do vectorized arithmetic on Z then. the hsv_to_rgb() function in colorsys does not support vectorized arithmetic, but the function with the same name in matplotlib.colors does, and the color map "afmhot" does exactly the coloring scheme you did in plot.py.

**Comment by Alexander-0x80** [comment]
Thank you for your input, what you saying is making sense.
if i'll get a chance i will address those issues ...

P.S if you have a modified version of your code a pull request would be fine too.. =)
